AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  FirstServerlessAPI

  Sample SAM Template for FirstServerlessAPI

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: java8
    MemorySize: 512
    Timeout: 30
    Environment:
      Variables:
        ORDERS_TABLE: !Ref OrdersTable

Resources:
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ordersapi
      Handler: com.vertigo.aws.lambda.apis.CreateOrderLambda::createOrder
      Policies:
        - DynamoDBCrudPolicy:
          TableName: !Ref OrdersTable
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
    ReadOrdersFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: ordersapi
        Handler: com.vertigo.aws.lambda.apis.ReadOrdersLambda::getOrders
        Policies:
          - DynamoDBReadPolicy:
            TableName: !Ref OrdersTable
        Events:
          OrderEvents:
            Type: Api
            Properties:
              Path: /orders
              Method: GET
Outputs:
  CreateOrdersAPI:
    Description: "API Gateway endpoint url for create orders function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com"
  CreateOrderFunction:
    Description: "Create Order Lambda Function ARN"
    Value: !GetAtt CreateOrderFunction.Arn
  CreateOrderFunctionIamRole:
    Description: "Create Order Lambda Function IAM Role ARN"
    Value: !GetAtt CreateOrderFunctionRole.Arn


# ------OLD TEMPLATE----------
#   HelloWorldFunction:
#     Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
#     Properties:
#       CodeUri: HelloWorldFunction
#       Handler: helloworld.App::handleRequest
#       Runtime: java8
#       MemorySize: 512
#       Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
#         Variables:
#           PARAM1: VALUE
#       Events:
#         HelloWorld:
#           Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#           Properties:
#             Path: /hello
#             Method: get

# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   HelloWorldApi:
#     Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#   HelloWorldFunction:
#     Description: "Hello World Lambda Function ARN"
#     Value: !GetAtt HelloWorldFunction.Arn
#   HelloWorldFunctionIamRole:
#     Description: "Implicit IAM Role created for Hello World function"
#     Value: !GetAtt HelloWorldFunctionRole.Arn
